# The Set_to_zero! routine

This notebook walks you through how to implement a simple function that sets all elements of a given matrix, 
stored in numpy matrix A, to zero.

## Getting started

We will use some functions that are part of our laff library (of which this function will become a part) as well as some routines from the FLAME API (Application Programming Interface) that allows us to write code that closely resembles how we typeset algorithms using the FLAME notation.  These functions are imported with `include` and `using` statements, as shown below.

## Algorithm

<img src="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/321ZeroAlgorithm.png" alt="Set matrix to zero algorithm" width="50%">

## The routine

The specific laff function we will use is `laff.zerov!` which, when given a row or column vector (stored as a 1 x n or n x 1 matrix) will zero that vector.  The vectors to be zeroed will actually be parts of the matrix A that we overwrite with zeroes.  

The flame functions should be self-explanatory if you put the below next to the algorithm for setting a matrix to the zero, expressed using the FLAME notation.

It is the `merge_1x2` routine that does require an explanation.  The problem is that we want to overwrite A with the result.  That routine takes `AT`, `AB`, and copies them back into `A`.

Follow along with the video, using the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a>.

In [8]:
include("../flame.jl")
using .flame
include("../laff/laff.jl")
using .laff

function Set_to_zero_unb_var1!(A)

    AL, AR = flame.part_1x2(A, 0, "LEFT")

    while size(AL, 2) < size(A, 2)

        A0, a1, A2 = flame.repart_1x2_to_1x3(AL, AR, 1, "RIGHT")

        #------------------------------------------------------------#

        laff.zerov!( a1 )
        
        #------------------------------------------------------------#

        AL, AR = flame.cont_with_1x3_to_1x2(A0, a1, A2, "LEFT")
    end
        
    flame.merge_1x2!(AL, AR, A)
end



Set_to_zero_unb_var1! (generic function with 1 method)

## Testing

Let's quickly test the routine by creating a 5 x 4 matrix and then setting it to zero.

In [9]:
A = rand(5, 4)

println( "A before =" )
A

A before =


5×4 Array{Float64,2}:
 0.590767    0.749948  0.588761   0.0539823
 0.799794    0.102504  0.348629   0.970215 
 0.98421     0.345566  0.0853492  0.232048 
 0.0601202   0.482655  0.938206   0.105751 
 0.00689654  0.673832  0.209214   0.695386 

In [10]:
Set_to_zero_unb_var1!( A )

println( "A after =" )
A

A after =


5×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

Bingo, it seems to work!

## Try it yourself (homework 3.2.1.2)

Now, one could alternatively set a matrix to zero by rows.

Use the <a href="https://studio.edx.org/c4x/UTAustinX/UT.5.01x/asset/index.html"> Spark webpage </a> to generate the function Set_to_zero_unb_var2( A ) that overwrites A with zeroes one row at a time.

In [11]:
include("../flame.jl")
using .flame
include("../laff/laff.jl")
using .laff

function Set_to_zero_unb_var2!(A)

    AT, 
    AB  = flame.part_2x1(A, 0, "TOP")

    while size(AT, 1) < size(A, 1)

        A0,
        a1t,
        A2   = flame.repart_2x1_to_3x1(AT,
                                       AB,
                                       1, "BOTTOM")

        #------------------------------------------------------------#

        laff.zerov!( a1t )
        
        #------------------------------------------------------------#

        AT,
        AB  = flame.cont_with_3x1_to_2x1(A0,
                                         a1t,
                                         A2,
                                         "TOP")
    end

    flame.merge_2x1!(AT, AB, A)
end



Set_to_zero_unb_var2! (generic function with 1 method)

Test your routine with the following

In [12]:
A = rand(5, 4)

print( "A before =" )
A

A before =

5×4 Array{Float64,2}:
 0.84031   0.634919  0.45746   0.300873
 0.569452  0.863485  0.159463  0.834408
 0.769623  0.743845  0.301008  0.628198
 0.793681  0.318207  0.475436  0.907526
 0.581166  0.94982   0.585088  0.825415

In [13]:
Set_to_zero_unb_var2!( A )
print( "A after =" )
A

A after =

5×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

## Watch your code in action!

Copy and paste the code into <a href="http://edx-org-utaustinx.s3.amazonaws.com/UT501x/PictureFlame/PictureFLAME.html"> PictureFLAME </a>, a webpage where you can watch your routine in action.  Just cut and paste into the box.  

Disclaimer: we implemented a VERY simple interpreter.  If you do something wrong, we cannot guarantee the results.  But if you do it right, you are in for a treat.

If you want to reset the problem, just click in the box into which you pasted the code and hit "next" again.