## Implementing a (vector) copy routine

### Preliminaries

<p><font color=red> Copy this notebook so that you don't corrupt the original!  Then you can "play" with the copy of the notebook all you want! </font> </p>

<p>This particular notebook does everything for you if you follow along with the video and type in code produced there.  You will be able to try it yourself in subsequent notebooks that implement other operations.</p>

Let's start by importing the `LinearAlgebra` package and creating a vector $ x = \left( \begin{array}{r} 1 \\ 2 \\ 3 \end{array} \right) $ and a vector $ y = \left( \begin{array}{r} 0 \\ -1 \\ -2 \end{array} \right) $.  

Execute the code in the box by clicking in the box and then on "Cell -> Run".  Alternatively, click on the box and push "Shift" and "Return" (or "Enter") together.

In [3]:
# This loads a package called `LinearAlgebra` that will make working with matrices 
# simpler.
using LinearAlgebra

# create 1D arrays or `Vector`s `x` and `y`
x = [1, 2, 3]
println("x = ", x)

y = [0, -1, -2]
println("y = ", y)

x = [1, 2, 3]
y = [0, -1, -2]


***A note on printing arrays***

First, notice that if we simply execute a cell containing the name of a `Vector` we've declared, the formatting indicates that it is a column vector:

In [4]:
x

3-element Array{Int64,1}:
 1
 2
 3

Whereas `println(x)` prints `x` so that it looks like a row.

In [5]:
println(x)

[1, 2, 3]


If we're happy with the row-like formatting, we could try `@show x;` instead of `println("x = ", x)`.

In [6]:
@show x;

x = [1, 2, 3]


and if we would like to print `x` so it *looks* like the column vector it is, we can use the function `Base.print_array()` from Julia's `Base`, which will take `stdout` as its first input argument:

In [7]:
println("x = ")
Base.print_array(stdout, x)

x = 
 1
 2
 3

Let's import `print_array` from `Base` and use it to print arrays going forward.

In [8]:
import Base.print_array
println("x = ")
print_array(stdout, x)

x = 
 1
 2
 3

For the rest of this notebook, we'll use the `@show` version for simplicity.

***Back to the assignment***

Now, let's use assignment to copy x into vector y:

(Again: "Shift" and "Return" at the same time!)

In [9]:
y=x

println("y = ")
print_array(stdout, y)

y = 
 1
 2
 3

Hmmm, it seems like it all worked.  The problem is that, in this situation, Julia does a "shallow copy".  If you change a value in x, then that value also changes in y.  In other words, y is just a reference to the same data that x references.

We illustrate this by setting the second entry in $ x $ to a new value and printing both <code> x </code> and <code> y </code>.

In [10]:
x[2] =  -999       # notice that Julia starts indexing at 1.  (You count 1, 2, 3, ...)
                   # Given a vector `x` of length n, x[2] refers to the second 
                   # component of vector x. 
println("x = ")
print_array(stdout, x)

println("\ny = ")
print_array(stdout, y)

x = 
    1
 -999
    3
y = 
    1
 -999
    3

To fix this, we could write a loop that copies the entries of x into the vector y.  Let's start by resetting the values in y:

In [11]:
x = [1, 2, 3]
y = [0, -1, -2]

println("x = ")
print_array(stdout, x)

println("\ny = ")
print_array(stdout, y)

x = 
 1
 2
 3
y = 
  0
 -1
 -2

Now, we want to copy the three entries in x into the three entries in y using a "for" loop:

In [12]:
for i in 1:3     # This executes the second line for i = 1, 2, 3
                 # So, 1:3 is the interval of integers [1, 3], inclusive of 3.
    y[ i ] = x[ i ] 
end

println("\ny = ")
print_array(stdout, y)


y = 
 1
 2
 3

If we now change the second value in x, the contents of y do not change:

In [13]:
x[ 2 ] = -999
println("x = ")
print_array(stdout, x)

println("\ny = ")
print_array(stdout, y)

x = 
    1
 -999
    3
y = 
 1
 2
 3

### Copy as a simple routine

Clearly, writing the "for loop" every time you want to copy a vector would be very cumbersome.  For this reason, we are going to write a routine, copy( x, y ), that copies the contents of vector x to vector y.  <font color=red> (Note: there <i>are</i> other ways of doing a "deep copy" in Julia.  However, the whole point of writing these routines is to help learn the material in this course.  This is not a course in which we teach you Julia beyond what you need to better understand linear algebra.) </font>

Here is what it means to copy a vector of size $ m $:
$$
\left( \begin{array}{c}
\psi_1 \\
\psi_2 \\
\vdots \\
\psi_{m}
\end{array}
\right)
:=
\left( \begin{array}{c}
\chi_1 \\
\chi_2 \\
\vdots \\
\chi_{m}
\end{array}
\right)
$$

As an algorithm this can be written as
<p>
<b> for </b> $ i = 1, \ldots , m $  <br>
 $ ~~~ \psi_i := \chi_i $ <br>
<b> endfor </b>
</p>

<p>
This translates into the following routine:
</p>

In [14]:
function copy!( x, y )
    # Check how many elements there are in vector x.  For this, 
    # length( x ) returns the number of elements in x    
    m = length(x)
    
    # now copy the elements
    for i in 1:m
        y[ i ] = x[ i ]
    end
end

copy! (generic function with 1 method)

*Be sure the run the above box, or this notebook won't know about the routine!!!*

Note that `copy!` has a `!` (a "bang") at the end of its name. In Julia, this is our way of reminding ourselves and others that `copy!` is a **mutating** function -- one that updates its input arguments. Here the second input argument is mutated: it will be equal to `x` after the function call even if it wasn't beforehand!

Now, if you execute

In [33]:
copy!( x, y )

println("x = ")
print_array(stdout, x)

println("\ny = ")
print_array(stdout, y)

x = 
 1
 2
 3
y = 
 1
 2
 3

you notice that vector x has been copied to vector y.  And if we change values in x, the values in y don't change:

In [34]:
x[ 3 ] = 111

println("x = ")
print_array(stdout, x)

println("\ny = ")
print_array(stdout, y)

x = 
   1
   2
 111
y = 
 1
 2
 3

### A complete copy function

As we develop our library, we want to be able to copy rows from a matrix into a column vector, columns of a matrix into a vector, a row of a matrix into a column of a matrix, and all such combinations.  As a result, what we really want is a copy routine that works when x and y are column and/or row vectors, in all combinations.  It also should notify us if we try to copy between vectors that are not of the same size.  The copy function below will accept both column vectors and row vectors (transpositions of column vectors) as input arguments. It checks that its input arguments have the same numbers of elements.

In [46]:
"""
    copy!(x, y)

Compute y = x, overwriting y.

x and y can be arrays with the same number of elements. For example,
x and y may both be columns vectors (`Vector`s) and/or row vectors
(transposed `Vector`s) of the same length.
"""
function copy!( x, y )
    n = length(x)
    @assert n == length(y) "x and y have different numbers of elements!"

    for i in 1:n
        y[ i ] = x[ i ]
    end
end

copy!

### Test the code

#### Copy a row to a row

In [36]:
# We can get a row vector by calling `transpose()` on a column vector
x = transpose([1, 2, 3])
y = transpose([0, -2, -3])

println("x = ")
print_array(stdout, x)

println("\ny = ")
print_array(stdout, y)

copy!( x, y )
println("\ny = ")
print_array(stdout, y)

@assert x == y

x = 
 1  2  3
y = 
 0  -2  -3
y = 
 1  2  3

In [37]:
println("-----SLAP_copy tests-----\n")

x = transpose([1, 2, 3])
y = transpose(fill(0, 3)) # create a vector of zeros and transpose it
# y = transpose(zeros(Int64, 3)) # Alternatively could have used `zeros()`

println("From row to row")
println("x = ")
print_array(stdout, x)
println("\ny = ")
print_array(stdout, y)

copy!(x,y)
println("\nAfter copying:")
println("y = ")
print_array(stdout, y)

-----SLAP_copy tests-----

From row to row
x = 
 1  2  3
y = 
 0  0  0
After copying:
y = 
 1  2  3

In [38]:
x = [1, 2, 3]
y = fill(0, 3)

println( "From column to column")
println("x = ")
print_array(stdout, x)
println("\ny = ")
print_array(stdout, y)

copy!(x,y)
println("\nAfter copying:")
println("y = ")
print_array(stdout, y)

From column to column
x = 
 1
 2
 3
y = 
 0
 0
 0
After copying:
y = 
 1
 2
 3

In [39]:
x = transpose([1, 2, 3])
y = fill(0, 3)

println( "From row to column")
println("x = ")
print_array(stdout, x)
println("\ny = ")
print_array(stdout, y)

copy!(x,y)
println("\nAfter copying:")
println("y = ")
print_array(stdout, y)

From row to column
x = 
 1  2  3
y = 
 0
 0
 0
After copying:
y = 
 1
 2
 3

In [40]:
x = [1, 2, 3]
y = transpose(fill(0, 3))

println( "From column to row")
println("x = ")
print_array(stdout, x)
println("\ny = ")
print_array(stdout, y)

copy!(x,y)
println("\nAfter copying:")
println("y = ")
print_array(stdout, y)

From column to row
x = 
 1
 2
 3
y = 
 0  0  0
After copying:
y = 
 1  2  3

Now, let's see what happens if we try to do something like copying a row of the wrong length into a column.  <font color="red"> Don't worry about the fact that you are getting error messages.  The whole point of the next few cells is to illustrate how errors are reported. </font>

In [41]:
println("-----SLAP_copy tests-----")

x = transpose([1, 2, 3, 4])
y = transpose(fill(0, 3))
println("From row to row")

println("x = ")
print_array(stdout, x)
println("\ny = ")
print_array(stdout, y)

copy!(x,y)
println("\nAfter copying:")
println("y = ")
print_array(stdout, y)

-----SLAP_copy tests-----
From row to row
x = 
 1  2  3  4
y = 
 0  0  0

BoundsError: BoundsError: attempt to access 3-element Array{Int64,1} at index [4]

In [42]:
println("-----SLAP_copy tests-----")

x = [1, 2, 3, 4]
y = fill(0, 3)
println("From column to column")

println("x = ")
print_array(stdout, x)
println("\ny = ")
print_array(stdout, y)

copy!(x,y)
println("\nAfter copying:")
println("y = ")
print_array(stdout, y) 

-----SLAP_copy tests-----
From column to column
x = 
 1
 2
 3
 4
y = 
 0
 0
 0

BoundsError: BoundsError: attempt to access 3-element Array{Int64,1} at index [4]

In [43]:
println("-----SLAP_copy tests-----")

x = transpose([1, 2, 3, 4])
y = fill(0, 3)

println( "From row to column")
println("x = ")
print_array(stdout, x)
println("\ny = ")
print_array(stdout, y)

copy!(x,y)
println("\nAfter copying:")
println("y = ")
print_array(stdout, y)

-----SLAP_copy tests-----
From row to column
x = 
 1  2  3  4
y = 
 0
 0
 0

BoundsError: BoundsError: attempt to access 3-element Array{Int64,1} at index [4]

In [44]:
println("-----SLAP_copy tests-----")

x = [1, 2, 3, 4]
y = transpose(fill(0, 3))

println( "From column to row")
println("x = ")
print_array(stdout, x)
println("\ny = ")
print_array(stdout, y)

copy!(x,y)
println("\nAfter copying:")
println("y = ")
print_array(stdout, y)

-----SLAP_copy tests-----
From column to row
x = 
 1
 2
 3
 4
y = 
 0  0  0

BoundsError: BoundsError: attempt to access 3-element Array{Int64,1} at index [4]

Finally, let's see if we can copies rows and/or columns in matrices


In [45]:
println("-----SLAP_copy tests-----")

A = [1  2  3  4
     5  6  7  8
     9 10 11 12 ]
B = fill(0, (3, 4))

println("From row to row")
println("A = ")
print_array(stdout, A)
println("\nB = ")
print_array(stdout, B)

copy!(A[2,:],B[1,:])
println("\nAfter copying:")
println("B = ")
print_array(stdout, B)

-----SLAP_copy tests-----
From row to row
A = 
 1   2   3   4
 5   6   7   8
 9  10  11  12
B = 
 0  0  0  0
 0  0  0  0
 0  0  0  0
After copying:
B = 
 0  0  0  0
 0  0  0  0
 0  0  0  0

In [61]:
println("-----SLAP_copy tests-----")

A = [1  2  3  4
     5  6  7  8
     9 10 11 12 ]
B = fill(0, (3, 4))

println("From column to column")
println("A = ")
print_array(stdout, A)
println("\nB = ")
print_array(stdout, B)

copy!(A[:, 1],B[:, 2])
println("\nAfter copying:")
println("B = ")
print_array(stdout, B)

-----SLAP_copy tests-----
From column to column
A = 
 1   2   3   4
 5   6   7   8
 9  10  11  12
B = 
 0  0  0  0
 0  0  0  0
 0  0  0  0
After copying:
B = 
 0  0  0  0
 0  0  0  0
 0  0  0  0

**We aren't getting any error messages, but `B` didn't change in either of the two examples above! Why is that?**

Consider the following examples.

We've already seen that when we run `y = x`, we don't truly copy `x` into `y`:

In [68]:
x = [1, 2, 3, 4]
y = x
@show y
x[1] = 999
@show x
@show y

y = [1, 2, 3, 4]
x = [999, 2, 3, 4]
y = [999, 2, 3, 4]


4-element Array{Int64,1}:
 999
   2
   3
   4

Consider this new example, where we assign `y`, to a slice of `x` instead of `x` itself.

In [70]:
x = [1, 2, 3, 4]
y = x[1:3]
@show y
x[1] = 999
@show x
@show y;

y = [1, 2, 3]
x = [999, 2, 3, 4]
y = [1, 2, 3]


In this case, updating `x` did not update `y`!

When we assign a slice of `x` to `y`, we *actually* copy that slice, rather than simply giving a `view` of the array.

Look how this changes when we use the `@views` command!

In [71]:
x = [1, 2, 3, 4]
@views y = x[1:3]
@show y
x[1] = 999
@show x
@show y;

y = [1, 2, 3]
x = [999, 2, 3, 4]
y = [999, 2, 3]


Similarly, when we try to copy a column of `A` into `B` via

```julia
copy!(A[:, 1],B[:, 2])
```

we're not really passing columns of `A` and `B` to `copy!`. Instead, we're passing *copies of those columns* to `A` and `B`, so the `copy!` function isn't able to update `B` itself.

As with the above example, we can fix this using `@views`.

**How to copy between rows and columns of matrices**

In [48]:
println("-----SLAP_copy tests-----")

A = [1  2  3  4
     5  6  7  8
     9 10 11 12 ]
B = fill(0, (3, 4))

println("From row to row")
println("A = ")
print_array(stdout, A)
println("\nB = ")
print_array(stdout, B)

@views copy!(A[2,:],B[1,:])
println("\nAfter copying:")
println("B = ")
print_array(stdout, B)

-----SLAP_copy tests-----
From row to row
A = 
 1   2   3   4
 5   6   7   8
 9  10  11  12
B = 
 0  0  0  0
 0  0  0  0
 0  0  0  0
After copying:
B = 
 5  6  7  8
 0  0  0  0
 0  0  0  0

In [50]:
println("-----SLAP_copy tests-----")

A = [1  2  3  4
     5  6  7  8
     9 10 11 12 ]
B = fill(0, (3, 4))

println("From column to column")
println("A = ")
print_array(stdout, A)
println("\nB = ")
print_array(stdout, B)

@views copy!(A[:, 1],B[:, 2])
println("\nAfter copying:")
println("B = ")
print_array(stdout, B)

-----SLAP_copy tests-----
From column to column
A = 
 1   2   3   4
 5   6   7   8
 9  10  11  12
B = 
 0  0  0  0
 0  0  0  0
 0  0  0  0
After copying:
B = 
 0  1  0  0
 0  5  0  0
 0  9  0  0

## Copying rows and columns of matrices

We haven't discussed matrices yet.  For now, just think of them as two dimensional arrays of numbers.  We illustrate how our general copy routine can copy rows to columns, columns to columns, and so forth.

In [52]:
println("-----SLAP_copy tests-----")

A = [1  2  3  4
     5  6  7  8
     9 10 11 12 ]
B = fill(0, (4, 3))

println("From row to column")
println("A = ")
print_array(stdout, A)
println("\nB = ")
print_array(stdout, B)

@views copy!(A[2, :],B[:, 1])
println("\nAfter copying:")
println("B = ")
print_array(stdout, B)

-----SLAP_copy tests-----
From row to column
A = 
 1   2   3   4
 5   6   7   8
 9  10  11  12
B = 
 0  0  0
 0  0  0
 0  0  0
 0  0  0
After copying:
B = 
 5  0  0
 6  0  0
 7  0  0
 8  0  0

In [53]:
println("-----SLAP_copy tests-----")

A = [1  2  3  4
     5  6  7  8
     9 10 11 12 ]
B = fill(0, (4, 3))

println("From column to row")
println("A = ")
print_array(stdout, A)
println("\nB = ")
print_array(stdout, B)

@views copy!(A[:, 2],B[1, :])
println("\nAfter copying:")
println("B = ")
print_array(stdout, B)

-----SLAP_copy tests-----
From column to row
A = 
 1   2   3   4
 5   6   7   8
 9  10  11  12
B = 
 0  0  0
 0  0  0
 0  0  0
 0  0  0
After copying:
B = 
 2  6  10
 0  0   0
 0  0   0
 0  0   0

## The laff library <code> copy </code> routine

The above routine is part of a library routine as part of the `laff` library.  To use it you will have to execute

```julia
include("../laff/laff.jl")
using .laff
```

after which you can use the routine by calling

```julia
laff.copy!( x, y )
```

In [72]:
include("../laff/laff.jl")
using .laff

x = [1, 2, 3]
y = [-1, 0, 2]

laff.copy!( x, y )

println("x = ")
print_array(stdout, x)

println("\ny = ")
print_array(stdout, y)

x = 
 1
 2
 3
y = 
 1
 2
 3

<font color="red"> That's all!  Next, you will get to practice writing some code.  But don't panic: we'll get you through it. </font>